---

language: python
services: docker

install:
  - pip install ansible molecule yamllint ansible-lint docker mitogen
before_script:
  - cd ../
  - mv ansible-role-cis-rhel8 cis-rhel8
  - cd cis-rhel8

script:
  #- make all
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
